import { StyleSheet } from "react-native";

export const nasabahStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  header: {
    backgroundColor: "#fff",
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  scrollContainer: {
    flex: 1,
    paddingVertical: 20,
  },
  formSection: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 15,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
    marginBottom: 8,
  },
  requiredStar: {
    color: "#FF3B30",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    backgroundColor: "#fafafa",
    minHeight: 50,
  },
  inputDisabled: {
    backgroundColor: "#f0f0f0",
    color: "#999",
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  photoContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  photoButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#f0f0f0",
    borderWidth: 2,
    borderColor: "#ddd",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  photoButtonDisabled: {
    opacity: 0.6,
    backgroundColor: "#e0e0e0",
  },
  photoLoadingContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  photoLoadingText: {
    fontSize: 12,
    color: "#007AFF",
    marginTop: 8,
    textAlign: "center",
  },
  photoPreviewContainer: {
    position: "relative",
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
  },
  photoImage: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  removePhotoButton: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255, 59, 48, 0.9)",
    alignItems: "center",
    justifyContent: "center",
  },
  removePhotoText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  photoPlaceholderContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  photoIcon: {
    fontSize: 24,
    color: "#666",
    marginBottom: 5,
  },
  photoText: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  photoSubtext: {
    fontSize: 10,
    color: "#999",
    textAlign: "center",
    marginTop: 2,
  },
  photoInfoText: {
    fontSize: 12,
    color: "#28a745",
    textAlign: "center",
    marginTop: 5,
  },
  calculationSection: {
    backgroundColor: "#f8f9fa",
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  calculationTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#495057",
    marginBottom: 15,
    textAlign: "center",
  },
  calculationsContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 15,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  calculationsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#495057",
    marginBottom: 10,
  },
  calculationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  calculationLabel: {
    fontSize: 14,
    color: "#6c757d",
    flex: 1,
  },
  calculationValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#28a745",
    flex: 1,
    textAlign: "right",
  },
  saveButton: {
    backgroundColor: "#28a745",
    marginHorizontal: 20,
    marginVertical: 20,
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  saveButtonDisabled: {
    backgroundColor: "#ccc",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  buttonLoadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 12,
    marginTop: 5,
  },
  currencyInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    backgroundColor: "#fafafa",
    minHeight: 50,
    textAlign: "right",
  },
  currencyDisplay: {
    fontSize: 14,
    color: "#28a745",
    fontWeight: "600",
    textAlign: "right",
    marginTop: 5,
  },
  validationContainer: {
    backgroundColor: "#fff3cd",
    borderWidth: 1,
    borderColor: "#ffeaa7",
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  validationText: {
    fontSize: 14,
    color: "#856404",
    textAlign: "center",
  },
  validationInfoText: {
    fontSize: 12,
    color: "#6c757d",
    marginTop: 5,
    fontStyle: "italic",
  },
});
